### ISSUE TITLE
[Video / Issue ]: Divi Theme Blog Posts Doesn't Let Video Lightbox Work

### ISSUE THREAD

**Issue by kelseymc** [archetyped/slb-addons#47] opened 2016-09-01 18:57 UTC
## Description of Problem

Hello!

I am currently using the Divi theme. I have a button on my slider that links to a video that pops up in a lightbox. However, if I add the blog entries to the page, the button acts as a normal link and just takes me to the youtube page of the video, instead of the video poping up in a lightbox.

## Details

* URL of Page exhibiting problem: currently a draft page from a website
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Firefox and Chrome
* Version of SLB Installed: 2.5.3, Video add on version: 0.2.0
* Other plugins installed: Yoast, Contact form 7, Divi 100 Hamburger Menu, Elegant Themes Updater, Google Analytics by MonsterInsights

**Comment by archetyped** [comment] 2016-09-02 02:46
Hi, I would love to help, unfortunately without a link to a page that exhibits the issue you are experiencing, I have no way to diagnosing the issue.  Please let me know when you have a link available and I would be glad to take a look.

**Comment by kelseymc** [comment] 2016-09-15 16:09
Hi,

I have a live link, but I don't have the blog currently up on the page because the video/plugin is more important than having the blog on the page.

Do you need the blog to be on the page in order to look at the code to see what's messing it up? Or could I just give you the link to the page as it is now?

**Comment by archetyped** [comment] 2016-09-15 22:48
Hi, any link is fine as long as it demonstrates the issue you are experiencing so that the cause can be investigated.

Thanks.

**Comment by kelseymc** [comment] 2016-09-21 17:16
Hello, here is a link to a test site/demo for the purpose of you looking at it, in hopes to fix the issue: https://www.noventri.net/medisign-test-site/

The link that utilizes the simple video add on is in the header, it is the first button that says, "Watch Full Video". As you can see the blog is present at the bottom of the page.

Please let me know what should be done to the actual site in order to actually fix the issue. As stated earlier, this is only a test site.

Thank you!

**Comment by archetyped** [comment] 2016-09-23 09:14
Hi, thank you for the link.  Just to confirm, without the blog posts on the page, the video is opened in the lightbox properly?   If so, then it appears that the blog module may be causing a conflict with SLB.

Please provide the steps you are taking to add the blog posts to the page so that I can reproduce the issue.  I have contacted Divi's developers to get a closer look at the theme, but as a paid theme, I unfortunately may not be able to investigate any further.

I will update this ticket when I have more information.

**Comment by kelseymc** [comment] 2016-09-23 12:40
Hello, yes, you are correct. When the blog module is not present on the page the SLB plugin works perfectly. It is only when I add the blog module to the page that it doesn't function properly. 

On the back-end I use the DIVI builder. I add a "Normal Section" and make it full width. I add the module that reads "Blog" and then I make it so that 6 blog posts are visible. I turn off the date, the author, the comments etc. I make sure a read button is present as well as the feature image and that an excerpt of the blog is shown. These are all features to use when selecting the blog module.

Please let me know if you need further information from me.

**Comment by archetyped** [comment] 2016-09-23 21:10
Thank you for the additional details.  It may be possible that one (or more) of the blog fields (title, image, etc.) are causing the conflict.  You can test this by removing each field one by one to see if SLB's functionality returns after each field is removed.  I would recommend starting by removing the **excerpt** field.

Let me know what you find, as it could help to resolve the issue faster once I am hopefully able to get a closer look at the theme you are using.

**Comment by archetyped** [comment] 2016-09-24 02:16
Hi, thanks to Divi's developers, I was able to take a closer look at what the theme is doing and confirmed that there is an issue with the blog module that stops plugins that process post/page content (such as SLB) from functioning properly.

I have reported the issue to Divi's developers, so hopefully the bug will be fixed soon.  If you are still experiencing this issue once the theme has been fixed, please post a comment and I would be glad to reopen this ticket and take another look.

**Closed by archetyped** 2016-09-24 02:16 UTC
Labels: compatibility, scope:external, support
